/**
 * Generate a SQL seed file from the committed `src/data/catalog.json` that
 * loads the feed-discovery catalog into the D1 `feeds` table.
 *
 * One-shot generator: reads the static catalog, computes the same `feedIdForUrl`
 * key + `normalizeUrl` feed_url the runtime uses, dedupes by id (first occurrence
 * wins, mirroring the runtime's INSERT OR IGNORE dedup), derives a favicon
 * icon_url from each feed's site URL, and writes `scripts/seed-catalog.sql`.
 * Apply it with the printed wrangler commands. Re-run `pnpm seed:catalog`
 * whenever the catalog changes — the emitted SQL is INSERT OR IGNORE, so it is
 * safe to apply repeatedly.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { faviconUrl, feedIdForUrl, normalizeUrl } from "../src/lib/url.ts";
import type { SeedFeed } from "../src/lib/types.ts";
import { categoryFor } from "./category-map.ts";

const here = dirname(fileURLToPath(import.meta.url));
const IN = join(here, "..", "src", "data", "catalog.json");
const OUT = join(here, "seed-catalog.sql");

/** Escape a value for a single-quoted SQL string literal, or NULL if absent. */
function sqlString(value: string | null | undefined): string {
	if (value == null) return "NULL";
	return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
	const feeds = JSON.parse(await readFile(IN, "utf8")) as SeedFeed[];
	const createdAt = Date.now();

	const seen = new Set<string>();
	const rows: string[] = [];
	let dedupedOut = 0;

	for (const feed of feeds) {
		const id = feedIdForUrl(feed.url);
		// First occurrence wins, matching the runtime's INSERT OR IGNORE dedup
		// and avoiding duplicate primary keys in a single batch.
		if (seen.has(id)) {
			dedupedOut++;
			continue;
		}
		seen.add(id);

		const feedUrl = normalizeUrl(feed.url);
		const iconUrl = faviconUrl(feed.siteUrl, feedUrl);

		const values = [
			sqlString(id),
			sqlString(feedUrl),
			sqlString(feed.title),
			sqlString(feed.siteUrl),
			sqlString(feed.description),
			sqlString(categoryFor(feed.category)),
			sqlString(iconUrl),
			sqlString("cataloged"),
			"0",
			String(createdAt),
		].join(", ");

		rows.push(
			`INSERT OR IGNORE INTO feeds (id, feed_url, title, site_url, description, category, icon_url, status, fetched_at, created_at) VALUES (${values});`,
		);
	}

	const header = [
		"-- Generated by scripts/seed-catalog.ts (pnpm seed:catalog). Do not edit by hand.",
		"-- Source: src/data/catalog.json. Statements are INSERT OR IGNORE, so this is safe to re-run.",
		`-- Generated at ${new Date(createdAt).toISOString()} (created_at = ${createdAt}).`,
		"",
	].join("\n");

	await mkdir(dirname(OUT), { recursive: true });
	await writeFile(OUT, `${header}${rows.join("\n")}\n`);

	console.log(`Read ${feeds.length} feeds from ${IN}`);
	console.log(`Deduped out ${dedupedOut} duplicate id(s)`);
	console.log(`Wrote ${rows.length} rows to ${OUT}`);
	console.log("");
	console.log("Apply it with:");
	console.log(
		"  local:  pnpm wrangler d1 execute scoop --local --file=scripts/seed-catalog.sql",
	);
	console.log(
		"  remote: pnpm wrangler d1 execute scoop --remote --file=scripts/seed-catalog.sql",
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
