/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryStoryIdRouteImport } from './routes/story.$storyId'
import { Route as RStoryIdRouteImport } from './routes/r.$storyId'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdRoute = StoryStoryIdRouteImport.update({
  id: '/story/$storyId',
  path: '/story/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const RStoryIdRoute = RStoryIdRouteImport.update({
  id: '/r/$storyId',
  path: '/r/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$storyId': typeof RStoryIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$storyId': typeof RStoryIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/inngest': typeof ApiInngestRoute
  '/l/$slug': typeof LSlugRoute
  '/r/$storyId': typeof RStoryIdRoute
  '/story/$storyId': typeof StoryStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/saved'
    | '/settings'
    | '/api/inngest'
    | '/l/$slug'
    | '/r/$storyId'
    | '/story/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/saved'
    | '/settings'
    | '/api/inngest'
    | '/l/$slug'
    | '/r/$storyId'
    | '/story/$storyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/saved'
    | '/settings'
    | '/api/inngest'
    | '/l/$slug'
    | '/r/$storyId'
    | '/story/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ApiInngestRoute: typeof ApiInngestRoute
  LSlugRoute: typeof LSlugRoute
  RStoryIdRoute: typeof RStoryIdRoute
  StoryStoryIdRoute: typeof StoryStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId': {
      id: '/story/$storyId'
      path: '/story/$storyId'
      fullPath: '/story/$storyId'
      preLoaderRoute: typeof StoryStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$storyId': {
      id: '/r/$storyId'
      path: '/r/$storyId'
      fullPath: '/r/$storyId'
      preLoaderRoute: typeof RStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ApiInngestRoute: ApiInngestRoute,
  LSlugRoute: LSlugRoute,
  RStoryIdRoute: RStoryIdRoute,
  StoryStoryIdRoute: StoryStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
